Feature: api Amazon search testing

  Scenario: Simple query
#    Given I set base url to "https://www.amazon.co.uk/"
    When I send a GET request to "s/ref=nb_sb_noss_2?url=search-alias%3Daps&field-keywords=simple"
    Then the response status should be 200
#    And the JSON response should be
#    """
#    {"location":"Sacramento, CA","timeZone":"PST","photoThumbUrl":"https://images.qa.ehealthinsurance.com/images/agents/test/thumb/CSR-outline-70x70.png","photoSmallUrl":"https://images.qa.ehealthinsurance.com/images/agents/test/small/CSR-outline-175x175.png","photoMediumUrl":"https://images.qa.ehealthinsurance.com/images/agents/test/medium/CSR-outline-300x300.png","agentSignature":null,"agentBio":{"learnMore":"Medicare sales is one of the most rewarding professions I have explored. I really enjoy assisting my clients by educating and navigating them in the process of making educated decisions about their health-care options. My day-to-day encounters with my clients are rewarding in lots of ways, helping me to sharpen my skills in so many different ways.","threeWords":"great guy","favThing":"great guy","favPlace":"great guy","helpingPeople":"The fulfillment of meeting the needs of my customer and making the process seamless for the customer. I get joy when they say ?I?m so happy I got you; you are awesome and very knowledgeable.? That tells me I am not working in vain. My objective is met when the customer is happy! My motto is ?if I meet the need of the customer, my financial needs will be met upon selling the plan.? So I focus on the customer first.","otherFav":null,"education":null,"hobbies":null},"agentId":2145,"firstName":"Bing","lastName":"Hu","email":"Bing.Hu@ehealth-china.com","workDays":"Mon - Fri","workDays2":null,"workStartTime":"8:30am","workStartTime2":null,"workEndTime":"5:30pm","workEndTime2":null,"videoUrl":null,"profileUrl":null,"licenseNumber":"ds","licensedSinceYear":"2015","languages":"English, Chinese","areaCode":"866","phone":"211-7443","workHours":"Mon - Fri, 8:30am - 5:30pm PST","workHours2":null,"extension":"5599","reviewCount":0,"helpful":null,"time":null,"knowledge":null,"listens":null,"courteous":null,"clearAdvice":null,"questions":null,"callAgain":null,"recommend":null,"topCustomerReview":null}
#    """